/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/Signup'
import { Route as LoginImport } from './routes/Login'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesNewImport } from './routes/recipes/New'
import { Route as RecipesRecipeIdImport } from './routes/recipes/$recipeId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/Signup',
  path: '/Signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesNewRoute = RecipesNewImport.update({
  id: '/recipes/New',
  path: '/recipes/New',
  getParentRoute: () => rootRoute,
} as any)

const RecipesRecipeIdRoute = RecipesRecipeIdImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/Signup': {
      id: '/Signup'
      path: '/Signup'
      fullPath: '/Signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdImport
      parentRoute: typeof rootRoute
    }
    '/recipes/New': {
      id: '/recipes/New'
      path: '/recipes/New'
      fullPath: '/recipes/New'
      preLoaderRoute: typeof RecipesNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Signup': typeof SignupRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/New': typeof RecipesNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Signup': typeof SignupRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/New': typeof RecipesNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Login': typeof LoginRoute
  '/Signup': typeof SignupRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/New': typeof RecipesNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Login' | '/Signup' | '/recipes/$recipeId' | '/recipes/New'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Login' | '/Signup' | '/recipes/$recipeId' | '/recipes/New'
  id:
    | '__root__'
    | '/'
    | '/Login'
    | '/Signup'
    | '/recipes/$recipeId'
    | '/recipes/New'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesNewRoute: typeof RecipesNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesNewRoute: RecipesNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Login",
        "/Signup",
        "/recipes/$recipeId",
        "/recipes/New"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Login": {
      "filePath": "Login.tsx"
    },
    "/Signup": {
      "filePath": "Signup.tsx"
    },
    "/recipes/$recipeId": {
      "filePath": "recipes/$recipeId.tsx"
    },
    "/recipes/New": {
      "filePath": "recipes/New.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
